version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:65:3c:86:e2:5c:64:82:d6:49:1f:4d:da:da:00:87"
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run deploy scripts
          command: bash ./deploy.sh
