name: Analyze Bundle (Comment)

on:
  workflow_run:
    workflows: ["Analyze Bundle"]
    types:
      - completed

jobs:
  judge:
    runs-on: ubuntu-latest
    steps:
     - name: Download Event Type
       uses: dawidd6/action-download-artifact@v2
       with:
        workflow: analyze.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: event_type
        path: event_type

     - name: get type
       id: get-type
       run: |
        event_type=$(cat event_type/event_type)
        echo "event-type=$event_type" >> $GITHUB_OUTPUT
        echo "event-type=$event_type" 

  comment:
    runs-on: ubuntu-latest
    needs: judge
    if: >
       github.event.workflow_run.workflow.conclusion == 'fail' && needs.judge.steps.get-type.outputs.event-type == 'pull_request' 
    steps:
      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: analyze.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: analysis_comment.txt
          path: analysis_comment.txt

      - name: Download PR number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: analyze.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_number
          path: pr_number

      - name: Get comment body
        id: get-comment-body
        if: success()
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '## Size changes' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '<details>' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          cat analysis_comment.txt/__bundle_analysis_comment.txt >> $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo '</details>' >>  $GITHUB_OUTPUT
          echo '' >>  $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          pr_number=$(cat pr_number/pr_number)
          echo "pr-number=$pr_number" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: success()
        id: fc
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body-includes: "<!-- __NEXTJS_BUNDLE -->"

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ steps.get-comment-body.outputs.pr-number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
